CREATE TABLE IF NOT EXISTS airports	(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	name VARCHAR(50) NOT NULL); 

CREATE TABLE IF NOT EXISTS planes (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	model VARCHAR(50) NOT NULL,
    seats INT NOT NULL); 

CREATE TABLE IF NOT EXISTS airlines (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	name VARCHAR(50) NOT NULL); 

CREATE TABLE IF NOT EXISTS passengers (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    idCard VARCHAR(50) NOT NULL,
	name VARCHAR(100)); 

CREATE TABLE IF NOT EXISTS flights (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    departure INT NOT NULL,
    departureDate TIMESTAMP,
	arrival INT NOT NULL,
    arrivalDate TIMESTAMP,
    plane INT,
    seatsOffered INT,
    airline INT NOT NULL); 

CREATE TABLE IF NOT EXISTS flight_scales (
	idFlight INT NOT NULL, 
    idAirport INT NOT NULL); 

CREATE TABLE IF NOT EXISTS flight_passengers (
	idFlight INT NOT NULL, 
    idPassenger INT NOT NULL); 


ALTER TABLE flights ADD CONSTRAINT FK_departure FOREIGN KEY(departure) REFERENCES flights(id);
ALTER TABLE flights ADD CONSTRAINT FK_arrival FOREIGN KEY(arrival) REFERENCES flights(id);
ALTER TABLE flights ADD CONSTRAINT FK_plane FOREIGN KEY(plane) REFERENCES planes(id);
ALTER TABLE flights ADD CONSTRAINT FK_airline FOREIGN KEY(airline) REFERENCES airlines(id);

ALTER TABLE flightScales ADD CONSTRAINT PK_flightScales PRIMARY KEY(idFlight, idAirport);
ALTER TABLE flightScales ADD CONSTRAINT FK_flights FOREIGN KEY(idFlight) REFERENCES flights(id);
ALTER TABLE flightScales ADD CONSTRAINT FK_airports FOREIGN KEY(idAirport) REFERENCES airports(id);

ALTER TABLE flightPassengers ADD CONSTRAINT PK_flightPassengers PRIMARY KEY(idFlight, idPassenger);
ALTER TABLE flightPassengers ADD CONSTRAINT FK_flights FOREIGN KEY(idFlight) REFERENCES flights(id);
ALTER TABLE flightPassengers ADD CONSTRAINT FK_passengers FOREIGN KEY(idPassenger) REFERENCES passengers(id);